# Generated by Django 4.1.1 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.IntegerField()),
                ("private", models.BooleanField(default=False)),
                ("room_name", models.CharField(max_length=128)),
                ("game_kind", models.IntegerField(default=0)),
                ("user_name", models.CharField(max_length=128)),
            ],
        ),
    ]
