# Generated by Django 4.1.2 on 2022-11-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_name', models.CharField(max_length=128)),
                ('private', models.BooleanField(default=False)),
                ('game_kind', models.IntegerField(default=0)),
                ('creator_name', models.CharField(max_length=128)),
                ('player_num', models.IntegerField(default=0)),
                ('viewer_num', models.IntegerField(default=1)),
                ('max_num', models.IntegerField(default=13)),
                ('status', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room.userinfo')),
                ('player_list', models.ManyToManyField(blank=True, related_name='player_list', to='room.userinfo')),
                ('viewer_list', models.ManyToManyField(blank=True, related_name='viewer_list', to='room.userinfo')),
            ],
        ),
    ]
