# Generated by Django 4.1.1 on 2022-10-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room", old_name="user_name", new_name="creator_name",
        ),
        migrations.AddField(
            model_name="room", name="max_num", field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name="room", name="player_num", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room", name="viewer_num", field=models.IntegerField(default=1),
        ),
    ]
