# Generated by Django 3.2.12 on 2022-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_user_name_room_creator_name_room_max_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
